### ISSUE TITLE
Extend page lifecycle events

### ISSUE THREAD

**Issue by indyjason79** [AvantiPoint/mauimicromvvm#7]
We are in the process of converting our XF app to Maui and were previously using Prism. I would prefer to use this library over Prism because we've ran into too many issues using it and just want a more simplified version. 

That being said, your library only exposes `OnAppearing` & `OnDisappearing` events to the view model. A ton of our existing code uses `OnNavigatedFrom` & `OnNavigatedTo` in the view models. 

Would it be possible for you to extend your `ViewLifecycle` with the rest of the page events or create a separate `PageLifecycle` class that does this? I've been trying to do this myself by looking at how you implemented your `ViewLifecycle`, but not having much luck.

**Comment by dansiegel** [comment]
Can you be a little more specific as to which events you're looking to handle.

**Comment by indyjason79** [comment]
- `NavigatedFrom`
- `NavigatedTo` 
- `NavigatingFrom`

In some of our view models we navigate to another page if a condition is met/not met. We need to be able to navigate after a page has **finished** navigation. 

I'm currently doing this in `OnAppearing` which is throwing the "Pending Navigations still processing" exception. To work around that I'm having to use the `Dispatcher` to defer navigation.

```
public class InitializationViewModel : ViewModelBase
{
    public InitializationViewModel(IViewModelContext context) : base(context) { }

    public override async void OnAppearing()
    {
        base.OnAppearing();

        if (Preferences.IsAuthenticated)
        {
            await this.NavigationService.GoHomeAsync();
        }
        else
        {
            Dispatcher.GetForCurrentThread()?.Dispatch(() => this.NavigationService.GoToPageAsync($"//{nameof(LoginPage)}"));
        }
    }
}
```

**Comment by dansiegel** [comment]
It's important to remember these two frameworks have fundamental differences. Prism handles a lot of things that Shell does not. With MauiMicro since we're using Shell there isn't current a concept for CanNavigate like in Prism which would be the closest to your NavigatingFrom. NavigatedFrom maps to OnDisappearing and NavigatedTo maps to OnAppearing. The MauiMicroViewModel does implement the Shell interface to set the parameters and you can hook into this with `OnParametersSet()` you can also do some initialization with `OnFirstSet()`.
